language: node_js
sudo: false
node_js:
- stable
addons:
  firefox: '42.0'
cache:
  directories:
  - node_modules
before_script:
- npm install web-component-tester bower polylint
- bower install
- bower install -s https://${GH_TOKEN}@github.com/Collaborne/collaborne-build-tools.git
- polylint
- export PATH=$PWD/node_modules/.bin:$PATH
script:
- xvfb-run wct
after_success: '[ ${TRAVIS_PULL_REQUEST} = "false" ] && [ ${TRAVIS_BRANCH} = "master" ] && bower_components/collaborne-build-tools/gpages_build.sh Collaborne info@collaborne.com'
env:
  secure: YXIJJGhxGAyCXAD0cjsoaDvREOkSmhVJuC1XYKppkM1LyqJdIN/OXMLSN2xIpdYSaEFL4CKn0hsvAYvWUG2YQClc0r3Fk4FfRGQ/2vmHwdWakbYTwZdYH7mo9x51qEkvSw5Jn9DPOq7EfN1qjb7btuCwwRo3j0beYQ9Z5DZ7VOmkDx9+5t2ou85kj2YOBD5pzjmvb0PuFA0GQLcWFB/1GRIPPYJD58u1BJl7w+h4aKxqJ8QkFzbOgL0dSaaCO9YbreIuNzOhojvQaE407ebwuR/twLOpo/MiLH9qX90i4+f11iBKzctcQzcjYIj9p+u30FoAGiXRJWM+vu3m8Gj0N2vKnKVXvhE80x0TAlzhCzYZyKYnuy5Ds7Xxn3ETNcgI/Qe685aQDme198ELT1+4WxQeVeDgM8iiAnmBgXlOV6SK18NFzUI1Zsd86RcTMv2ucwC090qHeY4VzhNmBADCTcx3G3kvfmj6MykzP6nwsUpNlgR58Y0bjiEs1fce/vlhPJnFJJZHBNInstxpRde7z8KTLu4JgEEBtWfZylQNE1JMqZ7XNsURcjA4uLGbeRz+3TDwr7yeNp1RjEgicMFxpnTr74oT7+loxw7QS8ebh+tfHB13C/uUk8aUx/4NdAiik/TiA8DotjBO0Io3t5irddk7sZTWVrqimaECTgLN/QE=
